### ISSUE TITLE
The explanation is unreadable for some options in the gui

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [SpaceWalkerRS/redstone-tweaks#3]
![image](https://user-images.githubusercontent.com/68545280/102012305-8cd6fb80-3d41-11eb-9927-3afbf6e51e7a.png)

![image](https://user-images.githubusercontent.com/68545280/102012317-982a2700-3d41-11eb-9c7a-bb57ea48e373.png)

![image](https://user-images.githubusercontent.com/68545280/102012324-a1b38f00-3d41-11eb-91e5-7ea6c6e1dc1a.png)

**Comment by DragonEggBedrockBreaking** [comment]
I don't understand what some of these options are because I can't read the description.

**Comment by DragonEggBedrockBreaking** [comment]
Note: This does not occur when I downscale my GUI to 3.

![image](https://user-images.githubusercontent.com/68545280/102012392-e5a69400-3d41-11eb-90b8-cb3a6cee6f64.png)

**Comment by SpaceWalkerRS** [comment]
Thank you for reporting! I will make the tooltips a bit less wide, that should hopefully remedy this issue.

**Comment by SpaceWalkerRS** [comment]
This should no longer be an issue in 0.9
